version: '3'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
    ports:
      - 8001:5432
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - 8002:6379
    env_file:
      - '.env'
volumes:
  redis:
  postgres: